UImate/urls.py
from django.contrib import admin
from django.urls import include, path
from tukerjakun.views import get_formulir, get_hasil_formulir

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('sso_ui.urls')),
    path('jakun/', include('tukerjakun.urls')),
    path('kenalan/', include('kenalan.urls')),
    path('passing/', include('PassingBarang.urls'), name= 'PassingBarang')
]

kenalan/urls.py
"""SSO UI urls module."""
from django.urls import path

from . import views

app_name = 'kenalan'
urlpatterns = [
    path('', views.index, name='index'),
    path('pertemuan/', views.daftar_pertemuan, name='daftar_pertemuan'),
    path('tambah/', views.tambah_pertemuan, name='tambah_pertemuan'),
    path('toggle_hadir/', views.toggle_hadir, name='toggle_hadir'),
    path('hapus/<int:id>/', views.hapus_pertemuan, name='hapus_pertemuan'),
    path('detail/<int:id>/', views.detail_pertemuan, name='detail_pertemuan'),
    path('komentar/<int:id>/', views.tambah_komentar, name='tambah_komentar'),
    path('ambil_komentar/<int:id>/', views.ambil_komentar, name='ambil_komentar'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kirim_pesan/', views.kirim_pesan, name='kirim_pesan'),
    path('randommessage/', views.random_message, name='random_message')
]

sso_ui/urls.py
"""SSO UI urls module."""
from django.urls import path
from django_cas_ng import views as cas_views

from . import views

app_name = 'sso_ui'
urlpatterns = [
    path('profile/<str:username>/', views.profile, name='profile'),
    path('login/', views.loginview, name="login"),
    path('signup/', views.signupview, name='signup'),
    path('loginapi/', views.loginapi, name="loginapi"),
    path('signupapi/', views.signupapi, name="signupapi"),
    path('nameapi/', views.nameapi, name="nameapi"),
    path('profileapi/', views.profileapi, name="profileapi"),
    path('loginsso/', cas_views.LoginView.as_view(), name='loginsso'),
    path('logoutsso/', cas_views.LogoutView.as_view(), name='logoutsso'),
]

sso_ui/models.py
"""SSO UI models module."""
import json

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_cas_ng.signals import cas_user_authenticated

LANG = settings.SSO_UI_ORG_DETAIL_LANG
ORG_CODE = {}
with open(settings.SSO_UI_ORG_DETAIL_FILE_PATH, 'r') as ORG_CODE_FILE:
    ORG_CODE.update(json.load(ORG_CODE_FILE))

color_names = ["Merah", "Jingga", "Kuning", "Hijau", "Biru", "Nila", "Ungu"]
colors = ["red", "orange", "yellow", "green", "blue", "purple", "violet"]

class Profile(models.Model):
    """User Profile model."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    org_code = models.CharField('kode organisasi', max_length=11, blank=True)
    role = models.CharField('peran pengguna', max_length=128, blank=True)
    npm = models.CharField('Nomor Pokok Mahasiswa', max_length=10, blank=True)
    faculty = models.CharField('fakultas', max_length=128, blank=True)
    study_program = models.CharField('program studi', max_length=128, blank=True)
    educational_program = models.CharField('program pendidikan', max_length=128, blank=True)
    color = models.CharField('warna tampilan', max_length=10, default="blue", choices=[(colors[x], color_names[x]) for x in range(len(colors))])
    picture = models.URLField('foto profil', default="https://avatarfiles.alphacoders.com/901/thumb-90193.png")

    class Meta:
        verbose_name = 'profil'
        verbose_name_plural = verbose_name

    def __str__(self):
        """Return username of the user."""
        return self.user.get_full_name() or "Pengguna Misterius"


@receiver(post_save, sender=User)
def create_user_profile(instance, created, **kwargs):
    """Create user profile if user object was just created."""
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(instance, **kwargs):
    """Save user profile post user save."""
    instance.profile.save()


@receiver(cas_user_authenticated)
def save_user_attributes(user, attributes, **kwargs):
    """Save user attributes from CAS into user and profile objects."""
    user.save()
    profile = user.profile
    profile.role = attributes['peran_user']
    profile.npm = attributes['npm']
    if profile.role == 'mahasiswa':
        user.email = f'{user.username}@ui.ac.id'

    full_name = attributes['nama']
    i = full_name.rfind(' ')
    user.first_name, user.last_name = full_name[:i], full_name[i + 1:]

    org_code = attributes['kd_org']
    record = ORG_CODE[LANG][org_code]
    profile.org_code = org_code
    profile.faculty = record['faculty']
    profile.study_program = record['study_program']
    profile.educational_program = record['educational_program']

    user.save()

sso_ui/forms.py
from django.forms import ModelForm, ChoiceField
from .models import Profile, User
from crispy_forms.helper import FormHelper

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['color', 'faculty', 'study_program', 'picture']
        
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False 

class NameForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name']

sso_ui/views.py
"""SSO UI views module."""
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest
from kenalan.models import Pertemuan
from .models import Profile, User
from .forms import ProfileForm, NameForm
import copy, random

original = {
    "description" : "Kenalan, Yuk!",
    "title" : "Kenalan, Yuk!",
    "need_login" : False
}

# @login_required(login_url='sso_ui:login')
def profile(request,username):
    if(request.method != "GET"):
        return HttpResponseBadRequest()
    profil = get_object_or_404(User, username=username).profile
    context = copy.copy(original)
    context["description"] = f"Profil {username}" 
    context["title"] = username
    context["profile"] = profil
    context["pertemuans"] = profil.peserta.all()
    if(request.user.is_authenticated and username==request.user.username):
        context["name_form"] = NameForm(request.POST or None, instance = request.user)
        context["form"] = ProfileForm(request.POST or None, instance=profil)
    return render(request, "profile.html", context)


def profileapi(request):
    if(request.is_ajax and request.method == "POST"):
        form = ProfileForm(request.POST, instance=request.user.profile)
        if(form.is_valid()):
            form.save()
            return JsonResponse({
            "status":200,
            "message":"Penggantian data profil berhasil ✔️",
            "fakultas":form.cleaned_data["faculty"],
            "jurusan":form.cleaned_data["study_program"],
            "warna":form.cleaned_data["color"],
            "picture":form.cleaned_data["picture"],
            })
        else:
            form = form.__str__()
            return JsonResponse({"status":400, "message":"Penggantian gagal 😵", "htmlform":form})
    return JsonResponse({"status":400, "message":"Server bermasalah 😵"})


def nameapi(request):
    if(request.is_ajax and request.method == "POST"):
        form = NameForm(request.POST, instance=request.user)
        # print(form)
        if(form.is_valid()):
            form.save()
            return JsonResponse({
            "status":200,
            "message":"Penggantian nama berhasil ✔️",
            "nama":form.cleaned_data["first_name"] + " " + form.cleaned_data["last_name"]})
        else:
            form = form.__str__()
            return JsonResponse({"status":400, "message":"Penggantian gagal 😵", "htmlform":form})
    return JsonResponse({"status":400, "message":"Server bermasalah 😵"})


def signupview(request):
    if(request.method != "GET"):
        return HttpResponseBadRequest()

    if(request.user.is_authenticated):
        return redirect('main:home')

    context = copy.copy(original)
    context["description"] = f"Daftar ke UImate"
    context["title"] = f"Daftar ke UImate"
    
    context["form"] = UserCreationForm()

    return render(request, "signup.html", context)

def loginview(request):
    if(request.method != "GET"):
        return HttpResponseBadRequest()

    if(request.user.is_authenticated):
        return redirect('main:home')

    context = copy.copy(original)
    context["description"] = f"Masuk ke UImate"
    context["title"] = f"Masuk ke UImate"
    context["form"] = AuthenticationForm()

    return render(request, "login.html", context)

def loginapi(request):
    if(request.is_ajax and request.method == "POST"):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        # print(user)
        # print(type(user))
        if user is not None:
            login(request, user)
            return JsonResponse({"status":200, "message":"Log in berhasil"})
        else:
            try:
                user = User.objects.get(username=username)
                return JsonResponse({"status":400, "message":"Password yang Anda masukkan salah ☹️"})
            except:
                return JsonResponse({"status":400, "message":"Akun dengan username ini tidak tersedia 👎"})
    return JsonResponse({"status":400, "message":"Server bermasalah 😵"})


def signupapi(request):

    if(request.is_ajax and request.method == "POST"):
        # print(request.POST)
        form = UserCreationForm(request.POST)
        if(form.is_valid()):
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(request, new_user)
            return JsonResponse({"status":200, "message":"Pendaftaran berhasil ✔️", "username":form.cleaned_data['username']})
        else:
            # print("Verdict__________________________________")
            form = form.__str__()
            # print(form)
            return JsonResponse({"status":400, "message":"Pendaftaran gagal 😵", "htmlform":form})

    return JsonResponse({"status":400, "message":"Server bermasalah 😵"})

sso_ui/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
<style>
    .asteriskField{
        display:none;
    }
</style>
{% endblock %}

{% block content %}
<section class="section-container d-flex flex-column dark-color align-items-center">
    <h1 class="animate__animated animate__pulse semi-bold-font pt-4">Masuk ke UImate</h1>

    {% include 'messages.html' %}
    <div class="card custom-card medium-card d-flex align-items-center justify-content-between">
        <form class = "mb-3 d-flex flex-column">
            {% csrf_token %}
            {{form | crispy}}
            <input class="btn btn-light m-1" id="login-button" type="button" value="Log in">
            <a class="btn btn-primary m-1" id="signup-button" href="{% url 'sso_ui:signup' %}">Daftar</a>
            <a class="btn btn-warning m-1" id="signup-button" href="{% url 'sso_ui:loginsso' %}">😊 Masuk dengan SSO UI</a>
        </form>
        <p class="d-flex text-center flex-row align-items-center" id="message-container"></p>
    </div>
</section>

{% endblock %}

{% block userscript %}
<script>
    $(document).ready(() => {
        $('#loader').hide();
        function login(username, password){
            $.ajax({
                url:"{% url 'sso_ui:loginapi' %}",
                type: "post",
                headers: {'X-CSRFToken': '{{ csrf_token }}'}, // for csrf token
                data: {'username':username, 'password':password},
                beforeSend: function() {
                    $("#message-container").html(`Mohon menunggu&nbsp;&nbsp;<img style="width: 20px;" src="{% static 'img/load.gif' %}" alt="Load">`)
                },
                success: function (response) {
                    if(response.status === 200){
                        window.location = "{% url 'sso_ui:profile' username='here' %}".replace('here', username);
                    }else{
                        $("#message-container").html(response.message)
                    }
                }
            })
        }
        $('#login-button').click(()=>{
            const username = $.trim($('#id_username').val());
            const password = $.trim($('#id_password').val());
            login(username, password);
        })
    });
</script>
{% endblock %}

sso_ui/templates/profile.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<section class="section-container d-flex flex-column align-items-center text-center" id="biodata">
  <img id="img-preview" class="m-3" src="{{profile.picture}}" alt="Preview"
    style="border-radius: 50%; border-style: solid; height: 250px; width: 250px; object-fit: cover; object-position: 50% 0;">
  <h1 id="nama" style="font-weight: 700; color: var(--main-{{ profile.color }});
	-webkit-text-stroke: 0.7px var(--main-dark-{{ profile.color }});
	-webkit-text-fill-color: var(--main-{{ profile.color }});">{{ profile }}</h1>
  <h3 id="jurusan-container" style="color: var(--main-dark-{{ profile.color }})">Jurusan <span id="jurusan">{{profile.study_program}}</span></h3>
  <h3 id="fakultas-container" style="color: var(--main-dark-{{ profile.color }})">Fakultas <span id="fakultas">{{profile.faculty }}</span></h3>
  {% if profile.user.username == user.username %}
  <div class="container-fluid">

    <form id="profile-form" class="card custom-card small-card align-items-center inlinedis {{profile.color}}">
      {% csrf_token %}
      <div class="d-flex flex-column align-items-center justify-content-center">
        <style>
          #div_id_color {
            margin: 0;
            margin-right: 5px;
          }
        </style>
        {{ form | crispy}}
        <input class="btn btn-dark mt-2" id="profile-button" type="button" value="Perbarui Profil">
      </div>
    </form>


    <form id="name-form" class="card custom-card small-card align-items-center inlinedis {{profile.color}}">
      {% csrf_token %}
      <div class="d-flex flex-column align-items-center justify-content-center">
        <style>
          #div_id_color {
            margin: 0;
            margin-right: 5px;
          }
        </style>
        {{ name_form | crispy}}
        <input class="btn btn-dark mt-2" id="name-button" type="button" value="Perbarui Nama">
      </div>
    </form>

    <style>
      .form-group {
        margin: 5px;
        width: 80%;
      }
    </style>
  </div>

  <div id="message" class="card custom-card small-card align-items-center {{profile.color}}">
    <p class="text-center" id="message-container">Perbarui profil kamu! 🌵</p>
  </div>

  <script src="{% static 'scripts/imageerror.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/js-xss/0.3.3/xss.min.js"
    integrity="sha512-M9w45qyI/KVHcxTODUsdwWip284UJBj2e6st1Ub6tXXO4nJAP3aIVN2Wkgd15CmJL6eJRFBSUssVyKtZX1v1Fg=="
    crossorigin="anonymous"></script>
  <script>
    $(document).ready(() => {
      xssOptions = {
        whiteList: [],        // empty, means filter out all tags
      }
      function recolor(color) {

        colors = ['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'violet'];
        for (tmpcolor of colors) {
          $("#profile-form").removeClass(tmpcolor)
          $("#name-form").removeClass(tmpcolor)
          $("#message").removeClass(tmpcolor)
          $("#gif-container").removeClass(tmpcolor)
        }
        $("#profile-form").addClass(color)
        $("#name-form").addClass(color)
        $("#message").addClass(color)
        $("#gif-container").addClass(color)
        $("#nama").attr('style', `font-weight: 700; color: var(--main-${color}); -webkit-text-stroke: 0.7px var(--main-dark-${color});-webkit-text-fill-color: var(--main-${color});`)
        $("#jurusan-container").attr('style', `color: var(--main-dark-${color})`)
        $("#fakultas-container").attr('style', `color: var(--main-dark-${color})`)

      }
      function updateName(form) {
        $.ajax({
          url: "{% url 'sso_ui:nameapi' %}",
          type: "post",
          headers: { 'X-CSRFToken': '{{ csrf_token }}' }, // for csrf token
          data: form,
          beforeSend: function () {
            $("input").removeClass("is-valid")
            $("input").removeClass("is-invalid")
            $("input").parent().children(".invalid-feedback").remove()
            $("#message-container").html(`Mohon menunggu&nbsp;&nbsp;<img style="width: 20px;" src="{% static 'img/load.gif' %}" alt="Load">`)
          },
          success: function (response) {
            if (response.status === 200) {
              $("#message-container").html(filterXSS(response.message, xssOptions))
              $("#nama").html(filterXSS(response.nama, xssOptions))
            } else {
              const field = ["first_name", "last_name"]
              response.htmlform = $.parseHTML(response.htmlform);
              $.each(field, function (fieldidx, fieldval) {
                const current = $(`[name='${fieldval}']`).parent();
                const formupd = $(response.htmlform).find(`[name='${fieldval}']`).parent();
                const errorlist = $(formupd).find(".errorlist > li")
                if (errorlist.length === 0) {
                  $(current).children("input").addClass("is-valid")
                } else {
                  $(current).children("input").addClass("is-invalid")
                  $.each(errorlist, function (erroridx, errorval) {
                    // console.log()
                    $(current).children("input").after(`<p class="invalid-feedback"><strong>${$(this).text()}</strong></p>`);
                  })
                }
              })
              $("#message-container").html(response.message)
            }
          }
        })
      }


      function updateProfile(form) {
        $.ajax({
          url: "{% url 'sso_ui:profileapi' %}",
          type: "post",
          headers: { 'X-CSRFToken': '{{ csrf_token }}' }, // for csrf token
          data: form,
          beforeSend: function () {
            $("input").removeClass("is-valid")
            $("input").removeClass("is-invalid")
            $("input").parent().children(".invalid-feedback").remove()
            $("#message-container").html(`Mohon menunggu&nbsp;&nbsp;<img style="width: 20px;" src="{% static 'img/load.gif' %}" alt="Load">`)
          },
          success: function (response) {
            if (response.status === 200) {
              $("#img-preview").attr("src", response.picture)
              $("#message-container").html(response.message)
              $("#jurusan").html(filterXSS(response.jurusan, xssOptions))
              $("#fakultas").html(filterXSS(response.fakultas, xssOptions))
              recolor(response.warna)
            } else {
              const field = ["color", "faculty", "study_program", "picture"]
              response.htmlform = $.parseHTML(response.htmlform);
              $.each(field, function (fieldidx, fieldval) {
                const current = $(`[name='${fieldval}']`).parent();
                const formupd = $(response.htmlform).find(`[name='${fieldval}']`).parent();
                const errorlist = $(formupd).find(".errorlist > li")
                if (errorlist.length === 0) {
                  $(current).children("input").addClass("is-valid")
                } else {
                  $(current).children("input").addClass("is-invalid")
                  $.each(errorlist, function (erroridx, errorval) {
                    // console.log()
                    $(current).children("input").after(`<p class="invalid-feedback"><strong>${$(this).text()}</strong></p>`);
                  })
                }
              })
              $("#message-container").html(response.message)
            }
          }
        })
      }
      $('#profile-button').click(() => {
        updateProfile($('#profile-form').serialize());
      })
      $('#name-button').click(() => {
        updateName($('#name-form').serialize());
      })
    });
  </script>

  <div id="gif-container" class="card custom-card small-card align-items-center {{profile.color}}">
    <input type="text" value="Funny" maxlength="128" class="textinput textInput form-control" id="gif-box">
    <strong class="mt-2 text-center">Pencet foto yang diinginkan untuk foto profil</strong>
  </div>

  <script>
    $(document).ready(() => {
      let keyPressed = 0;
      let pre = "";
      function cari(event) {
        if (this.value === pre) return;
        if (event.keyCode === 13) keyPressed = 0;
        if ((keyPressed++) % 5 !== 0) return;
        pre = this.value;
        $.ajax({
          url: `https://api.tenor.com/v1/search?q=${this.value}&limit=5`,
          success: function (response) {
            $(".pencarian").remove()
            for (foto of response.results) {
              $("#gif-container").append(
                `<img src="${foto.media[0].gif.url}"
                  alt="Gambar Pencarian" class="pencarian" style="margin: 1em; width: 70%; max-height: 400px; object-fit: cover; object-position: 50% 0;">`)
            }
            $(".pencarian").click(function () {
              console.log(this.src)
              $("#id_picture").attr("value", this.src);
              $("#profile-button").click()
              $("#message-container").html("Foto profil telah diperbarui ✔️")
            })
          },
        })
      }
      $("#gif-box").keyup(cari);
      $("#gif-box").keyup();
    });
  </script>

  {% endif %}
  {% if pertemuans %}
  <h2 style="font-weight: 700;">Pertemuan yang akan dihadiri</h2>
  {%for pertemuan in pertemuans %}

  <a class="card custom-card zoom small-card link-unstyled rainbow-card m-3 text-center"
    href="{% url 'kenalan:detail_pertemuan' id=pertemuan.id%}">
    <h2 style="font-weight: 700;">
      📢 {{ pertemuan }}
    </h2>

    <h3 class="m-0">
      👑 oleh {{ pertemuan.pembuat|default:" " }} <br>
      📆 {{ pertemuan.waktu_mulai|date:'l, d E Y' }} <br>
      ⏰ Pukul {{ pertemuan.waktu_mulai|date:'H:i' }} <br>
      ⏲️ {{ pertemuan.durasi }}
    </h3>
  </a>
  {% endfor %}
  {% endif %}
</section>
{% endblock content %}
{% block userscript %}
<script src="{% static 'scripts/rainbowcard.js' %}"></script>
{% endblock userscript %}

sso_ui/templates/signup.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block cdnscript %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
  crossorigin="anonymous" />
<style>
    .asteriskField{
        display:none;
    }
</style>
{% endblock %}

{% block content %}
<section class="section-container d-flex flex-column dark-color align-items-center">
    <h1 class="animate__animated animate__pulse semi-bold-font pt-4">Daftar ke UImate</h1>

    {% include 'messages.html' %}
    <div class="card custom-card medium-card d-flex align-items-center justify-content-between">
        <form class = "mb-3 d-flex flex-column" id="signup-form">
            {% csrf_token %}
            {{form | crispy}}
            <input class="btn btn-light" id="signup-button" type="button" value="Daftar">
        </form>
        <p class="d-flex text-center flex-row align-items-center" id="message-container"></p>
    </div>
</section>

{% endblock %}

{% block userscript %}
<script>
    $(document).ready(() => {
        function signup(form){
            $.ajax({
                url:"{% url 'sso_ui:signupapi' %}",
                type: "post",
                headers: {'X-CSRFToken': '{{ csrf_token }}'}, // for csrf token
                data: form,
                beforeSend: function() {
                    $("input").removeClass("is-valid")
                    $("input").removeClass("is-invalid")
                    $("input").parent().children(".invalid-feedback").remove()
                    $("#message-container").html(`Mohon menunggu&nbsp;&nbsp;<img style="width: 20px;" src="{% static 'img/load.gif' %}" alt="Load">`)
                },
                success: function (response) {
                    if(response.status === 200){
                        window.location = "{% url 'sso_ui:profile' username='here' %}".replace('here', response.username);
                    }else{
                        const field = ["username", "password1", "password2"]
                        response.htmlform = $.parseHTML(response.htmlform);
                        $.each(field, function(fieldidx, fieldval){
                            const current = $(`[name='${fieldval}']`).parent();
                            const formupd = $(response.htmlform).find(`[name='${fieldval}']`).parent();
                            const errorlist = $(formupd).find(".errorlist > li")
                            if(errorlist.length === 0){
                                $(current).children("input").addClass("is-valid")
                            }else{
                                $(current).children("input").addClass("is-invalid")
                                $.each(errorlist,function(erroridx, errorval){
                                    // console.log()
                                    $(current).children("input").after(`<p class="invalid-feedback"><strong>${$(this).text()}</strong></p>`);
                                })
                            }
                        })
                        $("#message-container").html(response.message)
                    }
                }
            })
        }
        $('#signup-button').click(()=>{
            signup($('#signup-form').serialize());
        })
    });
</script>
{% endblock %}